# Generated by Django 4.1.2 on 2022-10-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
